name: Shared Secrets
version: "1.0"
about: Aplicación para cifrar y decifrar documentos
author: Jonás García Chavelas & Daniel Linares Gil

# AppSettings can be defined as a list and are **not** ascii case sensitive
settings:
    - ArgRequiredElseHelp

subcommands:
    - c:
        about: Cifra un documento
        version: "1.0"
        args:
            - INPUT:
                help: Archivo a cifrar
                required: true
                index: 1
            - OUTPUT_NAME:
                help: Nombre para el archivo cifrado de salida y para el archivo de claves
                required: true
                index: 2
            - N:
                help: Numero total de fragmentos de clave a generar (N > 2)
                required: true
                index: 3
            - K:
                help: Numero minimo de fragmentos de clave necesarios para decifra el documento (0 < K <= N)
                required: true
                index: 4

    - d:
        about: Decifra un documento
        version: "1.0"
        args:
            - SHARES:
                help: Archivo que contiene los fragmentos de clave para decifrar
                required: true
                index: 2
            - ENCRYPTED_FILE:
                help: Documento cifrado con AES
                required: true
                index: 1
